### ISSUE TITLE
Write class files using Serde

### ISSUE THREAD

**Issue by Alfriadox** [Palmr/classfile-parser#16]
Could class files be written, as well as parsed, via [serde](https://crates.io/crates/serde) and [serde-bytes](https://docs.serde.rs/serde_bytes/index.html) ?
I could work on this...

**Comment by Palmr** [comment]
Potentially, I've not used serde/serde-bytes so can't comment but I'm not sure how easy they would be to use for this.

As far as I know serde is more for serialising/deserialising rust structs to/from other data formats, such as JSON, CBOR, XML, etc. I wasn't aware that you could take arbitrary data formats, like a java class file, and use serde to deserialise it into java objects? But as I say, I've not used it so might be wrong.

I started this project when I was learning to use the [nom](https://crates.io/crates/nom) crate, which is specifically made for parsing files like this in a nice rusty way and I thought that, as a java developer by day, I could learn a few things writing a java class file parser with it.

I think if you could do it and wanted to use serde/serde-bytes it would be best to make a new project for that rather than modify this project as it would have to be a total re-write anyway.

**Comment by Alfriadox** [comment]
Thank you for your insights! 

I am looking further into this, and have recently gained ownership of the [classreader crate](https://github.com/musiKk/classreader-rs) so I will probably implement it there.

Many thanks!

**Comment by Palmr** [comment]
No worries, I look forward to checking out the new classreader crate and see how it looks and compares.
